quarkus:
  http:
    port: 8080
    read-timeout: 30m
    limits:
      max-body-size: 5G

  package:
    type: uber-jar

  # Logging (disable console on prod)
  log:
    level: INFO
    min-level: TRACE
    category:
      "org.jboss":
        level: WARN
      "io.quarkus":
        level: WARN
      "io.smallrye":
        level: WARN
      "org.eclipse":
        level: WARN
      "io.netty":
        level: WARN
      "org.infinispan":
        level: WARN
      "io.agroal":
        level: WARN
      "org.commonjava.indy.service":
        level: INFO
    console:
      enable: true
    file:
      level: INFO
      enable: true
      path: "log/indy-archive-service.log"
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      rotation:
        max-backup-index: 5
        max-file-size: 10M

  swagger-ui:
    always-include: true

pre-seed:
  main-indy: https://indy-gateway-master-devel.psi.redhat.com
  storage-dir: data